/**
 * THE PINYIN LANE — the shipped artifact, the loader's guards, and the setting's storage.
 * L31 v2.1b+c, S4.
 *
 * ── WHY THE ARTIFACT IS ASSERTED HERE AND NOT ONLY IN THE BUILD STEP ────────────────────────────
 *
 * `scripts/build-pinyin.mjs` validates what it writes, and the map is gitignored, so it is always
 * freshly generated — which protects it from a hand-edit but NOT from a wrong generation. The step
 * runs against whatever `build-zh.mjs` produced and against whatever `pinyin-pro` version happens
 * to be installed; a dictionary re-curation, a moved pin, or a half-run build all produce a map the
 * build step is content with. So the claims the UI makes about this file — "one reading per atlas
 * id", "{n} in all", "generated by pinyin-pro@X" — are asserted here against the file that is
 * actually on disk, beside the number About prints from it.
 *
 * (The header first said "the file is committed", which is false: `.gitignore:46` ignores the whole
 * of `/public/i18n/`. Corrected rather than quietly deleted, because a test file that misdescribes
 * its own subject is how the next reader inherits the wrong model.)
 *
 * The completeness claim is the one worth having: EVERY Chinese name in the dictionary has a
 * reading, and every reading belongs to a name. A map that is 90% complete looks fine on the rows
 * anyone checks and shows nothing on the rest — the failure mode a spot check cannot see.
 */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {existsSync, readFileSync} from 'node:fs';

/**
 * ⚠️ `/public/i18n/` IS GITIGNORED — it is written by `build-zh.mjs` and `build-pinyin.mjs` at
 * deploy time (.gitignore:46). So a tree produced by `git archive HEAD` — which is exactly the tree
 * a codex review reads — does NOT contain the map, and an unconditional `readFileSync` here would
 * throw at import time and take all twelve of these tests down.
 *
 * That is precisely the artefact RC15 records: codex round 9's "181 passed, 3 failed" was a
 * review-snapshot effect (no `node_modules`), not a real red, and it cost a round to establish. So
 * the artifact-dependent tests SKIP with a named reason, loudly, and the loader and storage tests —
 * which need no generated file — always run. A skip that says why is evidence; a green that
 * silently asserted nothing is the thing this whole suite exists to refuse.
 */
const read = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url), 'utf8'));
const has = (p) => existsSync(new URL(p, import.meta.url));
const BUILT = has('../public/i18n/pinyin.json') && has('../public/i18n/zh-Hans.json');
const NEED_BUILD = BUILT
  ? false
  : 'public/i18n/ is gitignored (generated by build-zh.mjs + build-pinyin.mjs) — run both, or this is a source-only snapshot';
const MAP = BUILT ? read('../public/i18n/pinyin.json') : {version: 0, source: '', library: '', py: {}, counts: {concepts: 0, parts: 0, systems: 0}};
const HANS = BUILT ? read('../public/i18n/zh-Hans.json') : {concepts: {}, parts: {}, systems: {}};
const PKG = read('../package.json');
const HAN = /[㐀-䶿一-鿿豈-﫿]/;

test('the shipped map declares its version, source and the library that produced it', {skip: NEED_BUILD}, () => {
 assert.equal(MAP.version, 1);
 assert.equal(MAP.source, 'zh-Hans');
 // THE PIN AND THE STAMP MUST AGREE. `--save-exact` puts a bare version in devDependencies; if a
 // later `npm install` moves it without the map being rebuilt, About would name a library version
 // that did not produce the readings being shown. That is the exact drift About exists to prevent.
 const pinned = PKG.devDependencies['pinyin-pro'];
 assert.ok(pinned, 'pinyin-pro must be a pinned devDependency');
 assert.match(pinned, /^\d+\.\d+\.\d+$/, `the pin must be exact, not a range: ${pinned}`);
 assert.equal(MAP.library, `pinyin-pro@${pinned}`,
  'the map was generated by a different version than the one now pinned — rerun scripts/build-pinyin.mjs');
});

test('every reading is non-empty and fully romanised', {skip: NEED_BUILD}, () => {
 const ids = Object.keys(MAP.py);
 assert.ok(ids.length > 5000, `expected the whole atlas, got ${ids.length}`);
 const empty = ids.filter((id) => !MAP.py[id]);
 assert.deepEqual(empty, [], 'an empty reading renders as a blank line under a name');
 // A LEFTOVER HAN CHARACTER is half a romanisation presented as a whole one.
 const partial = ids.filter((id) => HAN.test(MAP.py[id]));
 assert.deepEqual(partial.slice(0, 5), [], 'these readings still contain Han characters');
 // And the padding the library emits around unconverted characters ("dì   3   yāo zhuī") is
 // collapsed — measured behaviour of pinyin-pro, not a guess.
 const padded = ids.filter((id) => /\s{2,}|^\s|\s$/.test(MAP.py[id]));
 assert.deepEqual(padded.slice(0, 5), [], 'these readings carry runs of whitespace');
});

test('COMPLETENESS, both ways: every Chinese name has a reading and every reading has a name', {skip: NEED_BUILD}, () => {
 const names = new Map();
 for (const [id, n] of Object.entries(HANS.concepts)) names.set(id, n);
 for (const [id, n] of Object.entries(HANS.parts)) if (!names.has(id)) names.set(id, n);
 for (const [id, e] of Object.entries(HANS.systems)) if (!names.has(id)) names.set(id, e.name);
 // (a) nothing with a Chinese name is missing a reading.
 const missing = [...names].filter(([id, n]) => HAN.test(n) && !MAP.py[id]).map(([id]) => id);
 assert.deepEqual(missing.slice(0, 5), [], `${missing.length} Chinese names have no reading`);
 // (b) no reading belongs to an id the dictionary does not carry — an orphan is a stale map.
 const orphan = Object.keys(MAP.py).filter((id) => !names.has(id));
 assert.deepEqual(orphan.slice(0, 5), [], `${orphan.length} readings name ids the dictionary does not have`);
 // (c) and the count About prints is the count that is in the file.
 const declared = MAP.counts.concepts + MAP.counts.parts + MAP.counts.systems;
 assert.equal(declared, Object.keys(MAP.py).length, 'the stamped counts disagree with the map');
});

test('the systems lane is present — the tree\'s top-level rows are Chinese names too', {skip: NEED_BUILD}, () => {
 assert.equal(MAP.counts.systems, Object.keys(HANS.systems).length);
 assert.ok(MAP.py.skeletal, 'the skeletal system has a reading');
 assert.ok(HAN.test(HANS.systems.skeletal.name));
});

test('the reading the live smoke reads: 胸骨体 is xiōng gǔ tǐ, as both concept and mesh', {skip: NEED_BUILD}, () => {
 assert.equal(HANS.concepts.FMA7487, '胸骨体');
 assert.equal(MAP.py.FMA7487, 'xiōng gǔ tǐ');
 // FJ3178 is the MESH of the same structure and must read the same — the two are one word.
 assert.equal(MAP.py.FJ3178, 'xiōng gǔ tǐ');
 // And a DIFFERENT structure must not share it: 胸骨 (Sternum) is two syllables, not three. This is
 // the assertion that catches a map keyed or sorted wrongly, which "it has 5,681 entries" cannot.
 assert.equal(MAP.py.FMA7485, 'xiōng gǔ');
});

// ── THE LOADER AND ITS GUARDS ───────────────────────────────────────────────────────────────────

/** One fetch stub per case, so a case cannot be influenced by another's. */
async function withFetch(impl, fn) {
 const prev = globalThis.fetch;
 globalThis.fetch = impl;
 try { return await fn(); } finally { globalThis.fetch = prev; }
}
const jsonRes = (body) => ({
 ok: true, headers: {get: (k) => (k.toLowerCase() === 'content-type' ? 'application/json; charset=utf-8' : null)},
 json: async () => body,
});

test('the loader REJECTS an HTTP 200 that is not JSON — the Pages SPA-shell trap', async () => {
 // Cloudflare Pages answers a missing static asset with the app's own HTML at HTTP 200 (measured on
 // this project in P2). `res.ok` is true, `json()` may even parse if the shell were JSON-ish, so
 // the content type is the discriminator. Without this a deploy that forgot the build step gives
 // every reader a toggle that turns on and shows nothing, with no error anywhere.
 const {loadPinyin, pinyinReady} = await import('../app/v2/pinyin.ts?case=spa');
 const got = await withFetch(
  async () => ({ok: true, headers: {get: () => 'text/html; charset=utf-8'}, json: async () => ({py: {X: 'x'}})}),
  () => loadPinyin(),
 );
 assert.equal(got, null, 'an HTML 200 must not be accepted as the map');
 assert.equal(pinyinReady(), false);
});

test('a FAILED load is retried on the next call, never memoised as "there is no pinyin"', async () => {
 const {loadPinyin} = await import('../app/v2/pinyin.ts?case=retry');
 let calls = 0;
 const first = await withFetch(async () => { calls++; throw new Error('network'); }, () => loadPinyin());
 assert.equal(first, null);
 assert.equal(calls, 1);
 // The same rule RC9 imposed on `loadZhDicts`: a rejection is not a fact about the atlas.
 const second = await withFetch(async () => { calls++; return jsonRes({version: 1, source: 'zh-Hans', library: 'x@1', py: {FMA7487: 'xiōng gǔ tǐ'}}); }, () => loadPinyin());
 assert.equal(calls, 2, 'the second call must really fetch again');
 assert.equal(second.py.FMA7487, 'xiōng gǔ tǐ');
});

test('a SUCCESSFUL load is fetched exactly once — the request-budget claim, at unit level', async () => {
 const {loadPinyin, pinyinReady, pinyinLibrary} = await import('../app/v2/pinyin.ts?case=once');
 let calls = 0;
 const body = {version: 1, source: 'zh-Hans', library: 'pinyin-pro@3.29.4', py: {FMA7487: 'xiōng gǔ tǐ'}};
 await withFetch(async () => { calls++; return jsonRes(body); }, async () => {
  // Concurrent callers share the in-flight promise; a later one is served from memory.
  await Promise.all([loadPinyin(), loadPinyin(), loadPinyin()]);
  await loadPinyin();
 });
 assert.equal(calls, 1, `one fetch for any number of callers, got ${calls}`);
 assert.equal(pinyinReady(), true);
 assert.equal(pinyinLibrary(), 'pinyin-pro@3.29.4');
});

test('A MALFORMED MAP IS REFUSED, NOT CACHED AS A SUCCESS — codex round 10, M4', async () => {
 /**
  * codex executed three counterexamples through the old guard, which only asked
  * `body.py && typeof body.py === 'object'`:
  *   · `{py: []}` became `ready:true` with zero readings — an array IS an object.
  *   · an OBJECT-valued reading escaped `pinyinOf`, whose return type says `string | null`, so a
  *     row would have rendered `[object Object]` under a structure's name.
  *   · wrong `version` / `source` metadata was accepted, i.e. a stale or foreign map.
  * And because the memo is set on success, each one was cached for the life of the page.
  *
  * None is reachable from `build-pinyin.mjs`, which validates what it writes. That is not the
  * question: this is a FETCH boundary, and the inputs it has to survive are a partial CDN body, a
  * hand-edited file and a future build whose shape moved.
  *
  * Each case gets a FRESH module instance, or the first success would mask the rest.
  */
 const cases = [
  ['an array for py', {version: 1, source: 'zh-Hans', library: 'x@1', py: []}],
  ['an EMPTY map', {version: 1, source: 'zh-Hans', library: 'x@1', py: {}}],
  ['an object-valued reading', {version: 1, source: 'zh-Hans', library: 'x@1', py: {A: {no: 1}}}],
  ['a numeric reading', {version: 1, source: 'zh-Hans', library: 'x@1', py: {A: 7}}],
  ['an empty-string reading', {version: 1, source: 'zh-Hans', library: 'x@1', py: {A: ''}}],
  ['a future version', {version: 2, source: 'zh-Hans', library: 'x@1', py: {A: 'a'}}],
  ['a foreign source', {version: 1, source: 'zh-Hant', library: 'x@1', py: {A: 'a'}}],
  ['no library stamp', {version: 1, source: 'zh-Hans', py: {A: 'a'}}],
  ['a bare array body', []],
  ['null', null],
 ];
 for (const [name, body] of cases) {
  const mod = await import(`../app/v2/pinyin.ts?m4=${encodeURIComponent(name)}`);
  const got = await withFetch(async () => jsonRes(body), () => mod.loadPinyin());
  assert.equal(got, null, `${name} must be refused`);
  assert.equal(mod.pinyinReady(), false, `${name} must not be cached as ready`);
  assert.equal(mod.pinyinLibrary(), null, `${name} must not let About name a library`);
  assert.equal(mod.pinyinOf('A', '胸骨体'), null, `${name} must not yield a reading`);
 }
 // AND A WELL-FORMED MAP IS STILL ACCEPTED, or the guard above would be satisfied by refusing
 // everything — which is the vacuous version of this test.
 const ok = await import('../app/v2/pinyin.ts?m4=good');
 const good = await withFetch(
  async () => jsonRes({version: 1, source: 'zh-Hans', library: 'pinyin-pro@3.29.4', py: {FMA7487: 'xiōng gǔ tǐ'}}),
  () => ok.loadPinyin(),
 );
 assert.equal(good.py.FMA7487, 'xiōng gǔ tǐ');
 assert.equal(ok.pinyinReady(), true);
});

test('pinyinOf gives NO reading for a Latin string — English never acquires a romanisation', async () => {
 const {loadPinyin, pinyinOf} = await import('../app/v2/pinyin.ts?case=han');
 await withFetch(async () => jsonRes({version: 1, source: 'zh-Hans', library: 'x@1', py: {FMA7487: 'xiōng gǔ tǐ'}}),
  () => loadPinyin());
 // The four surfaces each draw a DIFFERENT string for the same id (Chinese primary in a Chinese
 // interface, English primary with a Chinese pair in an English one), so the accessor is asked
 // about the text being drawn rather than about the interface language.
 assert.equal(pinyinOf('FMA7487', '胸骨体'), 'xiōng gǔ tǐ');
 assert.equal(pinyinOf('FMA7487', 'Body of sternum'), null, 'a Latin line must get nothing');
 assert.equal(pinyinOf('FMA7487', ''), null);
 assert.equal(pinyinOf('NOPE', '胸骨体'), null, 'an id with no reading gives null, not a guess');
});

test('pinyinOf gives nothing at all before the map has loaded', async () => {
 const {pinyinOf, pinyinReady, pinyinLibrary} = await import('../app/v2/pinyin.ts?case=cold');
 assert.equal(pinyinReady(), false);
 assert.equal(pinyinLibrary(), null, 'About must not name a library it has not seen');
 assert.equal(pinyinOf('FMA7487', '胸骨体'), null);
});

// ── atlas.pinyin — THE RC12 STORAGE CONTRACT ────────────────────────────────────────────────────

/** A localStorage stand-in. Node has none, which is itself one of the cases (`readPinyin` must not
 *  throw there — the same reason every access in `store.ts` is wrapped). */
function withStorage(value, fn) {
 const prev = globalThis.localStorage;
 const store = new Map(value === undefined ? [] : [['atlas.pinyin', value]]);
 globalThis.localStorage = {
  getItem: (k) => (store.has(k) ? store.get(k) : null),
  setItem: (k, v) => store.set(k, v),
  removeItem: (k) => store.delete(k),
 };
 try { return fn(store); } finally { globalThis.localStorage = prev; }
}

test('atlas.pinyin: a corrupt, wrong-typed or wrong-version value still renders, as OFF', async () => {
 const {readPinyin} = await import('../app/v2/shell/store.ts');
 // Each of these is a real shape somebody ships: a bare boolean (the obvious wrong design S0
 // rejected), a version from a future build, a truncated write, a type change.
 for (const bad of ['true', 'false', '{', '{"v":2,"on":true}', '{"v":1,"on":"yes"}', '[]', 'null', '"on"', '0']) {
  const got = withStorage(bad, () => readPinyin());
  assert.deepEqual(got, {v: 1, on: false}, `a corrupt value must fall back, not throw: ${bad}`);
 }
 // absent
 assert.deepEqual(withStorage(undefined, () => readPinyin()), {v: 1, on: false});
 // and a VALID value is respected, or the fallback above would be indistinguishable from ignoring
 // the key entirely — which is the vacuous version of this test.
 assert.deepEqual(withStorage('{"v":1,"on":true}', () => readPinyin()), {v: 1, on: true});
});

test('atlas.pinyin: the write is the shape the read accepts, and a throwing store is survivable', async () => {
 const {readPinyin, writePinyin, PINYIN_KEY} = await import('../app/v2/shell/store.ts');
 withStorage(undefined, (store) => {
  writePinyin({v: 1, on: true});
  assert.equal(store.get(PINYIN_KEY), '{"v":1,"on":true}');
  assert.deepEqual(readPinyin(), {v: 1, on: true}, 'round trip');
 });
 // Safari private browsing THROWS on setItem rather than returning. A toggle that takes the page
 // down there would be worse than a toggle that does not persist.
 const prev = globalThis.localStorage;
 globalThis.localStorage = {getItem: () => { throw new Error('SecurityError'); }, setItem: () => { throw new Error('SecurityError'); }};
 try {
  assert.deepEqual(readPinyin(), {v: 1, on: false});
  writePinyin({v: 1, on: true});   // must not throw
 } finally { globalThis.localStorage = prev; }
});
