/**
 * THE BUILD IDENTITY, WRITTEN ONCE PER BUILD — L34.
 *
 * usage: node scripts/build-id.mjs        (run by deploy.ps1 BEFORE `vite build`)
 *
 * WHAT THIS REPLACES, and why the replacement is the point of the increment.
 *
 * `SITE_BUILD` used to be a HAND-EDITED string literal in `workers/snap/wrangler.toml`. It is part
 * of the renderer's R2 cache key, so a render-path edit that forgot to move it served the PREVIOUS
 * build's pictures for the new build — at HTTP 200, with a plausible-looking picture, for as long as
 * the cache lived. That happened once for real (`p2` while the site had shipped P3 and P3r), and the
 * answer at the time was a tripwire in `deploy.ps1`: refuse the deploy if any file on a `renderPaths`
 * list is newer than the last commit that touched the toml. That guard then cost three "own commit"
 * SITE_BUILD bumps in L31 alone, each one an argued essay about whether a plate could have moved.
 *
 * The tripwire exists because the id could be forgotten. Derive the id and it cannot be:
 *
 *   git short hash, plus a digest of the uncommitted change when the tree is dirty
 *
 * Every commit is a new id, so every deploy retires exactly the pictures that a different commit
 * drew. A dirty tree gets its own id too, so a local `wrangler dev` render cannot land under the key
 * a committed build will later claim.
 *
 * ⚠️ THE COST IS STATED, NOT HIDDEN: the id now moves on EVERY commit, so every deploy is a cold
 * first render for each plate — where the hand-edited literal could deliberately stay put across a
 * commit that provably did not change a picture. That trade is taken on purpose. The old direction
 * failed silently (a wrong picture at 200); this one fails expensively and visibly (a slower first
 * render), and `plate-goldens.mjs compare` still proves the picture did not change.
 *
 * Deterministic and offline: two `git` reads and one file write. It writes the file only when the
 * contents would change, so it never touches the mtime of an unchanged build.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, 'worker', 'build-id.mjs');

const git = (args) => execFileSync('git', args, { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();

/**
 * `dev` is a truthful answer, not a fallback that hides a problem: a checkout with no git (a tarball,
 * a review snapshot) has no commit to name, and saying `dev` is better than inventing one. It is also
 * why `deploy.ps1` asserts a tree is clean AND that the id is not `dev` before it ships anything.
 */
/**
 * ⚠️ A DIRTY TREE'S ID IS DERIVED FROM ITS CONTENTS, NOT FROM A BOOLEAN — codex round 1, HIGH 2.
 *
 * The first version appended a constant "dirty" word. codex executed the consequence: edit a render file at
 * commit C and deploy with `-AllowDirty`, cache a plate; edit it AGAIN and deploy again — both
 * deployments are `C-dirty`, so the second is served the first one's picture. That is the exact
 * failure the derived id exists to make impossible, reintroduced by a flag that says only THAT the
 * tree differs and not HOW.
 *
 * So the suffix is a short digest of the uncommitted change itself: the porcelain status (which names
 * added, deleted and untracked paths) plus the tracked diff (which carries their contents). Two
 * different dirty states therefore differ. `test/snap-cache-key.test.mjs` asserts dirty-vs-DIFFERENT-
 * dirty, not merely clean-vs-dirty.
 *
 * ⚠️ WHAT IT STILL DOES NOT COVER, stated rather than implied: the CONTENTS of untracked files. A
 * diff cannot show them, so two dirty trees differing only inside the same untracked file share an id.
 * A clean deploy is the only fully-identified one, which is why `deploy.ps1` refuses a dirty tree
 * unless `-AllowDirty` is passed explicitly and says so on the way out.
 */
let id = 'dev';
try {
  const hash = git(['rev-parse', '--short', 'HEAD']);
  // `--porcelain` over the whole tree: an uncommitted edit ANYWHERE can change the bundle, so the
  // dirty flag is not scoped to a path list. Scoping it would re-create the renderPaths guess this
  // increment deletes.
  const status = git(['status', '--porcelain']);
  if (hash) {
    if (!status) id = hash;
    else {
      const diff = git(['diff', 'HEAD']);
      const digest = createHash('sha256').update(`${status}\n--\n${diff}`).digest('hex').slice(0, 10);
      id = `${hash}-${digest}`;
    }
  }
} catch { /* no git here — `dev` it is */ }

const body = `/**
 * GENERATED by scripts/build-id.mjs — DO NOT EDIT, and do not hand-bump it.
 *
 * This is the renderer's cache-key salt and the string Settings -> About prints. It is the git short
 * hash of the tree this artefact was built from; a dirty tree gets a second segment that is a digest
 * of the uncommitted change itself, so two different dirty states are two different ids. See
 * scripts/build-id.mjs for why it is derived rather than written down.
 */
export const SITE_BUILD = ${JSON.stringify(id)};
`;

mkdirSync(dirname(OUT), { recursive: true });
let existing = null;
try { existing = readFileSync(OUT, 'utf8'); } catch { /* first run */ }
if (existing !== body) writeFileSync(OUT, body);
console.log(`build id: ${id}${existing === body ? ' (unchanged)' : ''}`);
